Repository nopSolutions/nopCommerce, pull requests merged in 2019-05, with the labels that each got.

#3820 Features/rudgr/9 add blob and redis to system info admin
  src/Libraries/Nop.Core/Configuration/NopConfig.cs
  src/Presentation/Nop.Web.Framework/Infrastructure/DependencyRegistrar.cs
  src/Presentation/Nop.Web/Areas/Admin/Factories/CommonModelFactory.cs
  src/Presentation/Nop.Web/Areas/Admin/Models/Common/SystemInfoModel.cs
  src/Presentation/Nop.Web/Areas/Admin/Views/Common/SystemInfo.cshtml
  upgradescripts/4.10-4.20 (under development)/upgrade.sql
Labels: functionality / feature

#3793 #3736 Bugs/rudgr/3736 installation fails when run on mac
  src/Presentation/Nop.Web.Framework/Security/FilePermissionHelper.cs
Labels: refactoring / source code

#3814 Issue 3813 - Support globalization in alpine runtime
  Dockerfile
Labels: discussion / investigation

#3811 Issue 3810 Reapply commented and ignored tests
  src/Tests/Nop.Services.Tests/Messages/NewsLetterSubscriptionServiceTests.cs
  src/Tests/Nop.Web.MVC.Tests/Public/Validators/Blogs/BlogPostValidatorTests.cs
  src/Tests/Nop.Web.MVC.Tests/Public/Validators/Catalog/ProductReviewsValidatorTests.cs
Labels: refactoring / source code
