Repository nopSolutions/nopCommerce, pull requests merged in 2019-10, with the labels that each got.

#4082 issue-4081-chrome-problem-for-RTL-languages
  src/Presentation/Nop.Web/wwwroot/css/admin/styles.rtl.css
Labels: bug

#4078 AddShipment repeated code removed
  src/Presentation/Nop.Web/Areas/Admin/Controllers/OrderController.cs
Labels: refactoring / source code

#4074 Do not ignore email in GDPR when UsernamesEnabled
  src/Libraries/Nop.Services/ExportImport/ExportManager.cs
Labels: functionality / feature
