Repository nopSolutions/nopCommerce, pull requests merged in 2020-04, with the labels that each got.

#4472 Fix of #4423 - textbox accepts only numeric instead of characters
  src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Inventory.cshtml
Labels: discussion / investigation

#4243 lowercase non-western char from the seo char table
  src/Libraries/Nop.Services/Seo/UrlRecordService.cs
Labels: functionality / feature

#4582 Issue 4581 add aria labels for shopping cart and wishlist
  src/Presentation/Nop.Web/Views/Shared/Components/OrderSummary/Default.cshtml
  src/Presentation/Nop.Web/Views/ShoppingCart/Wishlist.cshtml
Labels: functionality / feature

#4232 Avalara: Use product name instead of description
  src/Plugins/Nop.Plugin.Tax.Avalara/AvalaraTaxProvider.cs
Labels: refactoring / source code

#4608 Removed duplicated html containers from Product Reviews Page to preve…
  src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.css
  src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.rtl.css
  src/Presentation/Nop.Web/Views/Product/ProductReviews.cshtml
Labels: refactoring / source code

#4610 Issue 4597 handling videos
  src/Libraries/Nop.Services/Media/RoxyFileman/BaseRoxyFilemanService.cs
Labels: functionality / feature
