Repository nopSolutions/nopCommerce, pull requests merged in 2020-10, with the labels that each got.

#4852 #4846
  src/Plugins/Nop.Plugin.Misc.SendinBlue/SendinBluePlugin.cs
Labels: refactoring / source code

#4976 virtual keyword missing in ReturnRequestService
  src/Libraries/Nop.Services/Orders/ReturnRequestService.cs
Labels: refactoring / source code

#4977 PR: Add UTM links
  src/Plugins/Nop.Plugin.Misc.SendinBlue/Views/Configure.cshtml
Labels: functionality / feature

#4982 Fix couple typos
  src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs
Labels: bug

#4984 Standardize customer use in GetProductAttributeValuePriceAdjustment
  src/Libraries/Nop.Services/Catalog/PriceCalculationService.cs
Labels: bug

#4999 remove unnecessary dash in front of blog post-date
  src/Presentation/Nop.Web/Views/Blog/List.cshtml
Labels: refactoring / source code

#5046 Update CheckoutModelFactory.cs
  src/Presentation/Nop.Web/Factories/CheckoutModelFactory.cs
Labels: refactoring / source code

#5068 GetAllCountries cache by store
  src/Libraries/Nop.Services/Directory/CountryService.cs
  src/Libraries/Nop.Services/Directory/NopDirectoryDefaults.cs
Labels: bug

#4965 Unsafe Cross-Origin Links #4961
  src/Presentation/Nop.Web/Views/Shared/Components/SocialButtons/Default.cshtml
Labels: refactoring / source code

#4810 #3835 billing address invalid css style fixed and the fix applied for…
  src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.css
  src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.rtl.css
Labels: refactoring / source code

#4836 Fixes #4821, adds 'back to' link for Shipping Methods page
  src/Presentation/Nop.Web/Areas/Admin/Views/Shipping/Methods.cshtml
Labels: functionality / feature

#4960 Plugins page. Rename "Is enabled" to "Enabled" #4775
  src/Plugins/Nop.Plugin.Misc.SendinBlue/Views/Configure.cshtml
  src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
Labels: refactoring / source code

#4289 Feature-3659 enable guest edit delete on checkout
  src/Presentation/Nop.Web/Controllers/CheckoutController.cs
  src/Presentation/Nop.Web/Extensions/MappingExtensions.cs
  src/Presentation/Nop.Web/Views/Checkout/BillingAddress.cshtml
  src/Presentation/Nop.Web/Views/Checkout/OnePageCheckout.cshtml
  src/Presentation/Nop.Web/Views/Checkout/OpcBillingAddress.cshtml
  src/Presentation/Nop.Web/Views/Shared/_CreateOrUpdateAddress.cshtml
  src/Presentation/Nop.Web/wwwroot/js/public.billingaddress.js
  src/Presentation/Nop.Web/wwwroot/js/public.countryselect.js
  src/Presentation/Nop.Web/wwwroot/js/public.onepagecheckout.js
Labels: on hold / maybe wont

#4016 Order Note Status Change Localization
  src/Libraries/Nop.Services/Orders/OrderProcessingService.cs
Labels: on hold / maybe wont

#4015 Check if headers are sent before setting cookie
  src/Presentation/Nop.Web.Framework/WebWorkContext.cs
Labels: refactoring / source code
