Repository nopSolutions/nopCommerce, pull requests merged in 2024-08, with the labels that each got.

#7277 Updated the province name of Nepal as per new naming
  src/Presentation/Nop.Web/App_Data/Localization/states.txt
Labels: functionality / feature

#7283 Fix db call in PermissionService.cs to async
  src/Libraries/Nop.Services/Security/PermissionService.cs
Labels: refactoring / source code

#7279 removing unused ILocalizedEnum interface #7275
  src/Libraries/Nop.Core/Domain/Localization/ILocalizedEnum.cs
Labels: refactoring / source code

#7288 Fix CI tests due to concurrency problems
  src/Tests/Nop.Tests/AssemblyInfo.cs
Labels: discussion / investigation
